spring.application.name=shipping-booking-service
server.port=8084

spring.datasource.url=${PRDDR_DB_URL:jdbc:h2:mem:shippingdb_prddr}
spring.datasource.username=${PRDDR_DB_USERNAME:sa}
spring.datasource.password=${PRDDR_DB_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
